export const UserActionTypes = {
  USER_LOADING: "USER_LOADING",
  USER_LOADED: "USER_LOADED",
  AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",
  START_LOGIN: "START_LOGIN",
  LOGIN_SUCCESSFUL: "LOGIN_SUCCESSFUL",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT_SUCCESSFUL: "LOGOUT_SUCCESSFUL"
};
